// Dependency-free gameplay regression checks. Run: node test-game.js
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const handlers={};const noop=()=>{};
const ctx=new Proxy({createLinearGradient:()=>({addColorStop:noop})},{get:(o,k)=>o[k]||noop,set:(o,k,v)=>(o[k]=v,true)});
const overlay={classList:{add:noop,remove:noop},querySelectorAll:()=>[],focus:noop};
const canvas={getContext:()=>ctx,addEventListener:noop,focus:noop,getBoundingClientRect:()=>({left:0,top:0,width:1100,height:700})};
const box={document:{querySelector:s=>s==='#game'?canvas:overlay},window:{addEventListener:(k,f)=>handlers[k]=f},requestAnimationFrame:noop,console,Math};vm.createContext(box);
vm.runInContext(fs.readFileSync(__dirname+'/game.js','utf8'),box);const run=s=>vm.runInContext(s,box);const key=k=>handlers.keydown({key:k,repeat:false,preventDefault:noop});
run('start();draw()');assert.equal(run('state'),'play');assert.equal(run('training'),true);
assert.equal(run('player.inventory.length'),1);assert.equal(run('hotbarEntries().length'),1);assert.equal(run('player.ammo'),0);
run('for(let i=0;i<1200;i++)update(1/60)');assert.equal(run('player.hp'),100);assert.equal(run('enemies.length'),2);
run('jump();jump();jump()');assert.equal(run('player.jumps'),2);
run('player.x=278;player.y=528;update(.016)');assert.equal(run('player.unlocked[1]'),true);assert.equal(run('player.inventory.length'),2);
run('player.weapon=1;player.cool=0;attack()');assert.equal(run('player.ammo'),0);assert.ok(run('bullets.length>0'));
key('Enter');assert.equal(run('state'),'map');assert.equal(run('training'),false);assert.equal(run('player.inventory.length'),1);
assert.equal(run('hotbarEntries().length'),1);assert.equal(run('player.swordLevel'),0);assert.equal(run('weaponDamage(0)'),18);
run('enterLevel(1)');assert.equal(run('state'),'map');run('enterLevel(0)');assert.equal(run('stage'),0);
assert.equal(run('LEVEL_LENGTH'),4800);assert.ok(run('platforms.length>=35'));
assert.ok(run('loot.find(l=>l.type==="weapon"&&l.weapon===1).x>1400'),'first gun should arrive later in Fernwood');
run('player.x=1538;player.y=528;update(.016)');assert.equal(run('player.unlocked[1]'),true);
assert.equal(run('player.inventory.length'),2);assert.ok(run('player.ammo>=28'));
run('player.x=1830;player.y=278;update(.016)');assert.equal(run('weaponDamage(0)'),36);
run('player.x=3288;player.y=528;update(.016)');assert.equal(run('player.unlocked[3]'),true);
run('player.x=2488;player.y=250;player.vy=0;player.ground=false;update(.016)');assert.equal(run('camps[0].used'),false,'passing above a rest stop should not activate it');
run('player.x=2488;player.y=528;player.vy=0;player.ground=true;update(.016)');assert.equal(run('camps[0].used'),true,'touching a rest stop on the ground should activate it');
assert.equal(run('player.inventory.length'),3);run('hotbarClick(19+2*119+35,640)');assert.equal(run('player.weapon'),3);
assert.equal(run('weapons[1].spread'),0);assert.ok(run('weapons[4].spread>weapons[1].spread&&weapons[4].cool<weapons[1].cool'));
run('player.weapon=5;player.cool=0;bullets=[];attack()');assert.equal(run('bullets.length'),6);
run('player.weapon=0;player.cool=0;player.attack=null;enemies=[];player.x=400;player.y=528;player.face=1;spawnMonster("slime",465);attack();for(let i=0;i<45;i++)tickMelee(.01)');
assert.equal(run('enemies[0].hp'),8);assert.equal(run('stageKills'),0);
run('player.attack=null;player.cool=0;mouse.x=10;camera=0;attack(true)');assert.equal(run('player.face'),-1,'mouse melee should face the pointer');
assert.equal(run('player.attack.face'),-1);
run('hit(enemies[0],100)');assert.equal(run('stageKills'),1);
run('player.hp=30;player.potions=1;heal()');assert.equal(run('player.hp'),75);
run('player.x=1230+16;player.y=528;player.vx=0;player.vy=0;player.ground=true;player.inv=0;keys.clear();const hpBefore=player.hp;update(.016)');assert.ok(run('player.hp<hpBefore'));
run('for(let i=stageKills;i<biomes[0].goal;i++){spawnMonster("slime",player.x+180);hit(enemies[enemies.length-1],1000)}');
assert.equal(run('stageKills'),run('biomes[0].goal'));
run('player.x=LEVEL_LENGTH-166;player.y=528;update(.016)');assert.equal(run('state'),'map');assert.equal(run('unlockedStage'),1);assert.equal(run('completed[0]'),true);
run('enterLevel(1)');assert.equal(run('stage'),1);assert.equal(run('player.unlocked[1]'),true);assert.equal(run('player.unlocked[2]'),false);
run('spawnMonster("scorpion",player.x+200);spawnMonster("beetle",player.x+250)');assert.equal(run('enemies[0].type'),'scorpion');assert.equal(run('enemies[1].type'),'beetle');
run('for(let i=0;i<biomes[1].goal;i++){spawnMonster("beetle",player.x+180);hit(enemies[enemies.length-1],1000)}');
run('player.x=LEVEL_LENGTH*2-166;player.y=528;update(.016)');assert.equal(run('state'),'map');assert.equal(run('unlockedStage'),2);
run('enterLevel(2);player.x=LEVEL_LENGTH*2+3710;update(.016)');assert.equal(run('bossSpawned'),true);assert.ok(run('enemies.some(e=>e.boss)'));
run('spawnTimer=999;enemies=enemies.filter(e=>e.boss);player.x=LEVEL_LENGTH*2+3780;player.y=178;player.vx=0;player.vy=0;player.inv=9;let bossLowY=FLOOR;for(let i=0;i<145;i++){update(.016);bossLowY=Math.min(bossLowY,enemies[0].y)}');
assert.ok(run('bossLowY<390'),'Warden should leap toward elevated players');
assert.ok(run('enemyShots.length>0'),'Warden should fire ranged volleys');
run('enemyShots=[{x:player.x-9,y:player.y+20,vx:0,vy:0,r:10,life:1,damage:14}];player.inv=0;player.hp=100;update(.016)');
assert.equal(run('player.hp'),86,'crystal projectiles should damage players on raised routes');
run('enemies[0].hp=400;enemyShots=[];wardenVolley(enemies[0])');assert.equal(run('enemyShots.length'),5,'the low-health phase should fire a wider volley');
run('enemyShots=[];wardenNova(enemies[0])');assert.equal(run('enemyShots.length'),12,'enraged Warden should have a distinct nova attack');
run('enemyShots=[];enemies[0].phaseTwo=true;enemies[0].attackIndex=2;enemies[0].bossCooldown=0;enemies[0].tell=0;updateWarden(enemies[0],.016)');assert.equal(run('enemies[0].queuedAttack'),'nova','the enraged phase should schedule nova');
run('enemies[0].hp=enemies[0].max;enemyShots=[]');
run('{const bigBoss=enemies[0];bigBoss.vx=0;spawnMonster("slime",bigBoss.x+200);spawnMonster("golem",bigBoss.x+300);const slime=enemies.find(e=>e.type==="slime"),golem=enemies.find(e=>e.type==="golem");knockback(slime,1,500,200);knockback(golem,1,500,200);knockback(bigBoss,1,500,200)}');
assert.ok(run('enemies.find(e=>e.type==="slime").knockVx>enemies.find(e=>e.type==="golem").knockVx&&enemies.find(e=>e.type==="golem").knockVx>enemies.find(e=>e.boss).knockVx'),'large, tough enemies should resist knockback');
run('const boss=enemies.find(e=>e.boss);hit(boss,82)');assert.ok(run('boss.hp>700'));
run('hit(boss,1000)');assert.equal(run('bossDefeated'),true);
run('for(let i=0;i<biomes[2].goal;i++){spawnMonster("golem",player.x+180);hit(enemies[enemies.length-1],1000)}');
run('player.x=WORLD-166;player.y=528;update(.016);draw()');assert.equal(run('state'),'win');
run('start();beginAdventure();enterLevel(0);player.hp=0;update(.016)');assert.equal(run('state'),'over');
run('start();beginAdventure();enterLevel(0);spawnTimer=999;player.x=1958;player.y=528;player.vy=0;player.ground=true;update(.016)');
assert.equal(run('player.vy'),0,'walking across a pad should not launch the player');
run('player.y=495;player.vy=400;player.ground=false;update(.08)');assert.ok(run('player.vy<-700'),'landing on a pad should launch the player');
run('player.x=1230;player.y=433;player.vy=0;player.ground=true;player.inv=0;const safeHp=player.hp;update(.016)');assert.equal(run('player.hp'),run('safeHp'),'floor traps should not hit players on overhead platforms');
for(const name of ['mushroom','wolf','beetle','scorpion','wisp','golem','warden','thorns','spikes','crystal-trap','log-platform','sandstone-platform','ruin-platform'])assert.ok(fs.existsSync(__dirname+'/assets/monsters/'+name+'.png'),name);
console.log('PASS: progression, landing-only pads, floor traps, scaled knockback, ranged and leaping Warden, and win/defeat.');




