// Dependency-free gameplay regression checks. Run: node test-game.js
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const handlers={},canvasListeners={};const noop=()=>{};
const mobileButtons=Object.fromEntries(['left','right','jump','attack','heal','map','pause','inventory','bar','prev','next'].map(action=>[action,{dataset:{control:action},listeners:{},classList:{add:noop,remove:noop},addEventListener(k,f){this.listeners[k]=f},setPointerCapture:noop}]));
const touch=(action,kind='pointerdown',x=100,y=100)=>mobileButtons[action].listeners[kind]({pointerId:7,clientX:x,clientY:y,preventDefault:noop,stopPropagation:noop});
const ctx=new Proxy({createLinearGradient:()=>({addColorStop:noop})},{get:(o,k)=>o[k]||noop,set:(o,k,v)=>(o[k]=v,true)});
const overlay={classList:{add:noop,remove:noop},querySelectorAll:()=>[],focus:noop};
const canvas={getContext:()=>ctx,addEventListener:(k,f)=>canvasListeners[k]=f,focus:noop,getBoundingClientRect:()=>({left:0,top:0,width:1100,height:700})};
const box={document:{querySelector:s=>s==='#game'?canvas:overlay,querySelectorAll:s=>s==='[data-control]'?Object.values(mobileButtons):[]},window:{addEventListener:(k,f)=>handlers[k]=f},requestAnimationFrame:noop,console,Math};vm.createContext(box);
vm.runInContext(fs.readFileSync(__dirname+'/game.js','utf8'),box);const run=s=>vm.runInContext(s,box);const key=k=>handlers.keydown({key:k,repeat:false,preventDefault:noop});
const canvasTouch=(kind,x,y,id=17)=>{const e={pointerId:id,pointerType:'touch',button:0,clientX:x,clientY:y,preventDefault:noop,stopPropagation:noop};if(kind==='pointerdown')handlers.pointerdown(e);if(kind==='pointermove')handlers.pointermove(e);canvasListeners[kind]?.(e);if(kind==='pointerup'||kind==='pointercancel')handlers[kind](e);};
const pickup=(level,offset)=>run('player.attack=null;player.cool=0;player.x='+((level*4800)+offset-12)+';player.y=528;player.vy=0;player.ground=true;update(.016)');
const clearLevel=()=>run('spawnTimer=999;enemies=[];for(let i=stageKills;i<biomes[stage].goal;i++){spawnMonster("slime",player.x+180);hit(enemies[enemies.length-1],1000)};player.x=(stage+1)*LEVEL_LENGTH-166;player.y=528;player.vx=0;player.vy=0;player.ground=true;update(.016)');
run('start();draw()');assert.equal(run('state'),'play');assert.equal(run('training'),true);
run('player.ground=true;player.jumps=0;player.coyote=0;player.attack=null;player.cool=0');
canvasTouch('pointerdown',400,400);canvasTouch('pointermove',400,330);assert.equal(run('player.jumps'),1,'first upward swipe jumps');assert.equal(run('player.attack'),null,'swipe does not attack');canvasTouch('pointerup',400,330);
canvasTouch('pointerdown',400,400);canvasTouch('pointermove',400,330);assert.equal(run('player.jumps'),2,'second upward swipe double jumps');canvasTouch('pointerup',400,330);
canvasTouch('pointerdown',400,400);canvasTouch('pointerup',400,400);assert.ok(run('player.attack'),'tap attacks once');assert.equal(run('mouse.down'),false);
run('player.attack=null;player.cool=0');canvasTouch('pointerdown',400,400);run('update(.2)');assert.ok(run('player.attack'),'holding attacks');assert.equal(run('mouse.down'),true);canvasTouch('pointerup',400,400);assert.equal(run('mouse.down'),false);
run('player.weapon=1;player.unlocked[1]=true;player.attack=null;player.cool=0');canvasTouch('pointerdown',400,400);run('update(.2)');assert.ok(run('player.cool>0'),'hold fires');run('update(.5)');assert.ok(run('player.cool>0'),'hold repeats');canvasTouch('pointerup',400,400);
run('player.weapon=0;player.unlocked[1]=false;player.attack=null;player.cool=0;player.jumps=0');
touch('right');assert.equal(run('keys.has("d")'),true);touch('right','pointerup');assert.equal(run('keys.has("d")'),false);
assert.equal(run('trainingLoot.length'),0,'advanced weapons are not in the camp');
run('for(let i=0;i<1200;i++)update(1/60)');assert.equal(run('player.hp'),100);assert.equal(run('enemies.length'),2);
key('Enter');assert.equal(run('state'),'map');assert.equal(run('player.inventory.length'),1);
run('enterLevel(1)');assert.equal(run('state'),'map');run('enterLevel(0)');assert.equal(run('stage'),0);
assert.equal(run('biomes.length'),6);assert.equal(run('completed.length'),6);assert.equal(run('WORLD'),28800);
assert.ok(run('platforms.length>=70'));assert.ok(run('biomes.every((_,i)=>loot.filter(l=>l.type==="weapon"&&Math.floor(l.x/LEVEL_LENGTH)===i).length===2)'),'two weapon finds in each level');
assert.equal(run('Math.floor(loot.find(l=>l.weapon===1).x/LEVEL_LENGTH)'),2,'pistol comes in level three');
assert.equal(run('Math.floor(loot.find(l=>l.weapon===4).x/LEVEL_LENGTH)'),4,'machine gun comes in level five');
assert.equal(run('Math.floor(loot.find(l=>l.weapon===2).x/LEVEL_LENGTH)'),5,'hammer comes in the final level');
const before=run('time');key('i');assert.equal(run('state'),'inventory');run('frame(100)');assert.equal(run('time'),before,'inventory freezes simulation');key('i');assert.equal(run('state'),'play');
touch('inventory');assert.equal(run('state'),'inventory','phone Pack button opens the pausing inventory');touch('inventory','pointerup');key('i');assert.equal(run('state'),'play');
pickup(0,1500);assert.equal(run('player.unlocked[7]'),true);assert.equal(run('player.inventory.length'),2);
pickup(0,3250);assert.equal(run('weaponDamage(0)'),36);
pickup(0,3600);assert.equal(run('player.unlocked[8]'),true);assert.equal(run('player.ammo'),0);
run('player.cool=0;bullets=[];attack()');assert.ok(run('bullets.length>0'),'pebble sling fires without scarce ammunition');
run('player.weapon=0;player.cool=0;player.attack=null;enemies=[];player.x=400;player.y=528;player.face=1;spawnMonster("slime",465);attack();for(let i=0;i<45;i++)tickMelee(.01)');
assert.equal(run('enemies[0].hp'),8);run('hit(enemies[0],100)');assert.equal(run('stageKills'),1);
run('player.x=2538;player.y=250;player.vx=0;player.vy=0;player.ground=false;update(.016)');assert.equal(run('camps[0].used'),false);
run('player.x=2538;player.y=528;player.vx=0;player.vy=0;player.ground=true;update(.016)');assert.equal(run('camps[0].used'),true);assert.equal(run('player.ammo'),0);
run('player.x=1230+16;player.y=528;player.vx=0;player.vy=0;player.ground=true;player.inv=0;keys.clear();const hpBefore=player.hp;update(.016)');assert.ok(run('player.hp<hpBefore'));
clearLevel();assert.equal(run('state'),'map');assert.equal(run('unlockedStage'),1);
run('enterLevel(1)');pickup(1,1600);assert.equal(run('player.unlocked[9]'),true);
pickup(1,2100);assert.equal(run('weaponDamage(0)'),54);pickup(1,3600);assert.equal(run('player.unlocked[3]'),true);
clearLevel();assert.equal(run('unlockedStage'),2);
run('enterLevel(2)');pickup(2,1200);assert.equal(run('player.unlocked[10]'),true);
run('player.attack=null;player.cool=0;player.face=1;attack()');assert.equal(run('player.inv>0'),true,'wind staff grants a brief escape window');assert.equal(run('player.vx<0'),true);
run('player.attack=null;player.cool=0;player.x=LEVEL_LENGTH*2+1800;player.vx=0;spawnMonster("slime",player.x+58);const escapeTarget=enemies[enemies.length-1];attack();for(let i=0;i<45;i++)tickMelee(.01)');assert.equal(run('escapeTarget.hp'),44,'wind staff does no damage');assert.ok(run('escapeTarget.knockVx>0'),'wind staff pushes enemies away');
pickup(2,3000);assert.equal(run('player.unlocked[1]'),true);assert.ok(run('player.ammo>=28'));
run('player.x=LEVEL_LENGTH*2+3710;update(.016)');assert.equal(run('bossSpawned'),true);assert.ok(run('enemies.some(e=>e.boss)'));
run('spawnTimer=999;enemies=enemies.filter(e=>e.boss);player.x=LEVEL_LENGTH*2+3780;player.y=178;player.vx=0;player.vy=0;player.inv=9;let bossLowY=FLOOR;for(let i=0;i<145;i++){update(.016);bossLowY=Math.min(bossLowY,enemies[0].y)}');
assert.ok(run('bossLowY<390'),'Warden reaches elevated players');assert.ok(run('enemyShots.length>0'),'Warden fires ranged volleys');
run('enemies[0].hp=400;enemyShots=[];wardenVolley(enemies[0])');assert.equal(run('enemyShots.length'),5);
run('enemyShots=[];wardenNova(enemies[0])');assert.equal(run('enemyShots.length'),12);
run('enemyShots=[];enemies[0].phaseTwo=true;enemies[0].attackIndex=2;enemies[0].bossCooldown=0;enemies[0].tell=0;updateWarden(enemies[0],.016)');assert.equal(run('enemies[0].queuedAttack'),'nova');
run('const boss=enemies.find(e=>e.boss);hit(boss,1000)');assert.equal(run('bossDefeated'),true);
clearLevel();assert.equal(run('state'),'map','the Warden is a midgame boss');assert.equal(run('unlockedStage'),3);
run('enterLevel(3)');pickup(3,1450);pickup(3,3420);assert.equal(run('player.inventory.length'),9);
assert.equal(run('player.loadouts[1][0]'),11,'extra gear spills onto second bar');
key('i');assert.equal(run('state'),'inventory');run('activeBar=1;selectedSlot=0;assignWeaponToSlot(0)');
assert.equal(run('player.loadouts[1][0]'),0);assert.equal(run('player.loadouts[0][0]'),11,'assignment swaps weapons between bars');
key('i');assert.equal(run('state'),'play');key('b');assert.equal(run('activeBar'),0);key('1');assert.equal(run('player.weapon'),11);
clearLevel();assert.equal(run('unlockedStage'),4);
run('enterLevel(4)');pickup(4,1600);pickup(4,3450);assert.equal(run('player.unlocked[4]'),true);
clearLevel();assert.equal(run('unlockedStage'),5);
run('enterLevel(5)');pickup(5,1600);pickup(5,3380);assert.equal(run('player.inventory.length'),13);
assert.equal(run('player.loadouts[0].filter(x=>x!==null).length+player.loadouts[1].filter(x=>x!==null).length'),13);
clearLevel();run('draw()');assert.equal(run('state'),'win');
run('start();beginAdventure();enterLevel(0);player.hp=0;update(.016)');assert.equal(run('state'),'over');
run('start();beginAdventure();enterLevel(0);spawnTimer=999;player.x=1958;player.y=528;player.vy=0;player.ground=true;update(.016)');
assert.equal(run('player.vy'),0,'walking across a pad should not launch the player');
run('player.y=495;player.vy=400;player.ground=false;update(.08)');assert.ok(run('player.vy<-700'),'landing on a pad should launch the player');
run('player.x=1230;player.y=433;player.vy=0;player.ground=true;player.inv=0;const safeHp=player.hp;update(.016)');assert.equal(run('player.hp'),run('safeHp'),'floor traps should not hit through platforms');
for(const name of ['mushroom','wolf','beetle','scorpion','wisp','golem','warden','thorns','spikes','crystal-trap','log-platform','sandstone-platform','ruin-platform'])assert.ok(fs.existsSync(__dirname+'/assets/monsters/'+name+'.png'),name);
console.log('PASS: six lands, staged weapon pickups, inventory pause and loadouts, mobile gestures, Warden, hazards, and victory.');
